---
title: "Laboratorio 1"
output: html_notebook
name: "Haroldo Pablo Arias Molina"
id: "999008683"
---


# Laboratorio 1

### Información General
- Nombre: Haroldo Pablo Arias Molina
- Registro: 999008683


# 1.VECTORES Y MATRICES
```{r}
#PASO 1.1 - CREACIÓN DE VECTORES
student_1 <- c(50.4, 62.3, 92.1, 77.6, TRUE)
student_2 <- c(41.7, 87.9, 75.3, 72.4, FALSE)
student_3 <- c(30.3, 67.8, 69.3, 71.2, FALSE)
student_4 <- c(65.4, 85.1, 92.3, 96.8, TRUE)
student_5 <- c(70.4, 88.2, 95.2, 90.7, TRUE)

#PASO 1.2 CREACIÓN DE VECTOR DE ESTUDIANTES
students_vector <- c(student_1, student_2, student_3, student_4, student_5)

#PASO. 1.3 CREACIÓN DE MATRIX DE ESTUDIANTES
students_matrix = matrix(students_vector, byrow=TRUE, nrow=5)
```

# 2.NOMBRADO DE UNA MATRIZ
```{r}
#PASO 2.1 CREACIÓN DE VECTORES DE NOMBRADO
name_students = c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age = c("TIC", "Accounting", "Psychology", "Ethics", "Legal_age")

#PASO 2.2 ASIGNACIÓN DE FILAS Y COLUMNAS
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <-name_students

students_matrix
```


# 3.rowSums, cbind
```{r}
#PASO 3.1 SE REALIZA LA SUMATORIA
total_grade_student = rowSums(students_matrix[, c(1, 2, 3, 4)])
total_grade_student


#PASO 3.2 UNION AL MATRIX PRINCIPAL
result_students <- cbind(students_matrix, total_grade_student) 
result_students
```

# 4. Seleccionando elementos de una matriz

```{r}
#PASO 4.1 SELECCION E IMPRESION DE DATOS
selected_elements = result_students[c(1,3,5) , c(2, 4)]
print(selected_elements)
```


# 5. Data frames
```{r}
#PASO 5.1 CREACIÓN DE UN DATA FRAME
students_grades_df = data.frame(result_students)
students_grades_df

#PASO 5.2 FILTRAR INFORMACIÓN
subset(students_grades_df, subset = Accounting > 80 & Legal_age == TRUE)

```


# 6. Funciones, Condicionales y Bucles
```{r}

#PASO 6.1 CREACIÓN DE FUNCIÓN
students_projection <- function(matriz) {
  for(i in 1:nrow(matriz)){
    for(j in 1:ncol(matriz)){
      # VALIDANDO UNICAMENTE LAS PRIMERAS 4 COLUMNAS
      if(j > 4){
        break
      }
      #PASO 6.2 CONDICIONES PARA IMPRESION
      if(matriz[i,j] <= 45){
        print("Student at risk")
      }else if(matriz[i,j] > 45 & matriz[i,j]<61){
        print("Student may be approved")
      }else if( matriz[i,j]>=61){
        print("Student approved")
      }
    }
  }
}


#PASO 6.3 PRUEBA FUNCIÓN
students_projection(result_students)

```

#7. Data frames y lapply
```{r}
#PASO 7.1 CONSTRUCCION DE FUNCION
index_education <- function(grade) {
  return((1+(grade/100))/2)
}

#PASO 7.2 FILTRADO DEL DATA FRAME
all_students_grade = students_grades_df[1:4]
all_students_grade

#PASO 7.3 USO DE FUNCIÓN Y LAPPLY
lapply(all_students_grade, index_education)
```

#8. Math utilities
```{r}
#PASO 8.1 PROMEDIO POR ESTUDIANTE

score_mean = apply(students_grades_df[1:4],1, mean)
score_mean
```


